In [118]:
import gpytorch.kernels as kernel
import torch
from src.test_statistics import *
from src.data import *
import random
import numpy as np

In [119]:
X_ker = kernel.RBFKernel()
Y_ker = kernel.RBFKernel()

In [120]:
X = torch.randn((10,2))
Y = torch.randn(10)
T = (torch.randn((10))>0).float()

In [121]:
data_train = Data_object(X,Y,T)
data_train_flip = Data_object(X,Y,1-T)

In [122]:
X = torch.randn((10,2))
Y = torch.randn(10)
T = (torch.randn((10))>0).float()

In [123]:
Y1 = torch.randn((1))

In [124]:
data_test = Data_object(X,Y,T)
data_test_flip = Data_object(X,Y,1-T)

In [125]:
W0 = get_W_matrix(X_ker(data_train.X0).evaluate(),1)
W1 = get_W_matrix(Y_ker(data_train.X1).evaluate(),1)

In [126]:
weights = 1/2*torch.ones(10)

In [127]:
K = ker(X_ker)
L = ker(Y_ker)

In [128]:
c = (data_test.T - weights)/(weights*(1-weights))
c

tensor([ 2., -2., -2., -2., -2., -2.,  2.,  2.,  2., -2.])

In [129]:
data_train.Y.shape

torch.Size([10])

In [130]:
L(data_train.Y0,data_train.Y).shape

torch.Size([7, 10])

In [131]:
DATE_test_stat(data_train,data_test,X_ker,Y_ker,weights,W0,W1)

22.431089401245117

In [132]:
DETT_test_stat(data_train,data_test,X_ker,Y_ker,weights,W1)

24.48888397216797

In [133]:
from sklearn.preprocessing import KBinsDiscretizer

In [134]:
weights = torch.randn(5)

In [135]:
binner = KBinsDiscretizer(n_bins=2,encode = "ordinal")

In [136]:
binner.fit(weights.reshape(-1,1))

KBinsDiscretizer(encode='ordinal', n_bins=2)

In [137]:
a = binner.transform(weights.reshape(-1,1))

In [138]:
(a == 1).squeeze(1)

array([ True,  True,  True, False, False])

In [139]:
(a == 1).squeeze(1)

array([ True,  True,  True, False, False])

In [149]:
def binned_permutation(weights, n_bins):
    perm = np.array((range(len(weights))))
    binner = KBinsDiscretizer(n_bins=n_bins,encode = "ordinal")
    binner.fit(weights.reshape(-1,1))
    binned_weights = binner.transform(weights.reshape(-1,1))
    for i in range(n_bins):
        bin_i = ((binned_weights == i).squeeze(1))
        print(bin_i)
        perm[ bin_i ] = random.shuffle(perm[ bin_i ])
    return perm


In [150]:
binned_permutation(weights,2)

[False False False  True  True]


TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

In [142]:
n_bins = 2
perm = np.array((range(len(weights))))
binner = KBinsDiscretizer(n_bins=n_bins,encode = "ordinal")
binner.fit(weights.reshape(-1,1))
binned_weights = binner.transform(weights.reshape(-1,1))


In [145]:
bin_i = ((binned_weights == 0).squeeze(1))

In [146]:
perm[bin_i]

array([3, 4])